import Head from 'next/head'
import Home from '../components/Home'

export default function HomePage() {
  return (
    <div >
      <Head>
        <title>BlockChain Bazaar</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

     <Home/>
    </div>
  )
}
